version: 0.2
phases:
  install:
    commands:
      # install required binary
      - wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
      - unzip terraform_0.13.5_linux_amd64.zip
      - mv terraform /usr/bin/
      - chmod +x /usr/bin/terraform
  pre_build:
    commands:
      - terraform --version
      - ls 
      - cd Terraform-Modules  
      - terraform init 
      - terraform destroy -auto-approve
     
      - terraform plan -out= . 
      - terraform apply -state=.  -auto-approve 
      - cd ..


  post_build: 
   commands:
      - ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[].[AutoScalingGroupName]' --output text)
      - aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME 